// Code generated by cmd/tools/gen.go; DO NOT EDIT.
package data

// ItemIDToName stores item IDs to names mapping for reverse lookup.
var ItemIDToName = make(map[int]string)

func init() {
	for name, id := range ItemNameToID {
		ItemIDToName[id] = name
	}
}

// GetItemName returns the name for an item ID.
func GetItemName(id int) (string, bool) {
	name, ok := ItemIDToName[id]
	return name, ok
}

// MaxStackSizeTable stores stack sizes for items that are not 64.
var MaxStackSizeTable = map[int]int{
	int(552):  1,  // Shulker Box (shulker_box)
	int(553):  1,  // White Shulker Box (white_shulker_box)
	int(554):  1,  // Orange Shulker Box (orange_shulker_box)
	int(555):  1,  // Magenta Shulker Box (magenta_shulker_box)
	int(556):  1,  // Light Blue Shulker Box (light_blue_shulker_box)
	int(557):  1,  // Yellow Shulker Box (yellow_shulker_box)
	int(558):  1,  // Lime Shulker Box (lime_shulker_box)
	int(559):  1,  // Pink Shulker Box (pink_shulker_box)
	int(560):  1,  // Gray Shulker Box (gray_shulker_box)
	int(561):  1,  // Light Gray Shulker Box (light_gray_shulker_box)
	int(562):  1,  // Cyan Shulker Box (cyan_shulker_box)
	int(563):  1,  // Purple Shulker Box (purple_shulker_box)
	int(564):  1,  // Blue Shulker Box (blue_shulker_box)
	int(565):  1,  // Brown Shulker Box (brown_shulker_box)
	int(566):  1,  // Green Shulker Box (green_shulker_box)
	int(567):  1,  // Red Shulker Box (red_shulker_box)
	int(568):  1,  // Black Shulker Box (black_shulker_box)
	int(801):  1,  // Saddle (saddle)
	int(802):  1,  // White Harness (white_harness)
	int(803):  1,  // Orange Harness (orange_harness)
	int(804):  1,  // Magenta Harness (magenta_harness)
	int(805):  1,  // Light Blue Harness (light_blue_harness)
	int(806):  1,  // Yellow Harness (yellow_harness)
	int(807):  1,  // Lime Harness (lime_harness)
	int(808):  1,  // Pink Harness (pink_harness)
	int(809):  1,  // Gray Harness (gray_harness)
	int(810):  1,  // Light Gray Harness (light_gray_harness)
	int(811):  1,  // Cyan Harness (cyan_harness)
	int(812):  1,  // Purple Harness (purple_harness)
	int(813):  1,  // Blue Harness (blue_harness)
	int(814):  1,  // Brown Harness (brown_harness)
	int(815):  1,  // Green Harness (green_harness)
	int(816):  1,  // Red Harness (red_harness)
	int(817):  1,  // Black Harness (black_harness)
	int(818):  1,  // Minecart (minecart)
	int(819):  1,  // Minecart with Chest (chest_minecart)
	int(820):  1,  // Minecart with Furnace (furnace_minecart)
	int(821):  1,  // Minecart with TNT (tnt_minecart)
	int(822):  1,  // Minecart with Hopper (hopper_minecart)
	int(823):  1,  // Carrot on a Stick (carrot_on_a_stick)
	int(824):  1,  // Warped Fungus on a Stick (warped_fungus_on_a_stick)
	int(826):  1,  // Elytra (elytra)
	int(827):  1,  // Oak Boat (oak_boat)
	int(828):  1,  // Oak Boat with Chest (oak_chest_boat)
	int(829):  1,  // Spruce Boat (spruce_boat)
	int(830):  1,  // Spruce Boat with Chest (spruce_chest_boat)
	int(831):  1,  // Birch Boat (birch_boat)
	int(832):  1,  // Birch Boat with Chest (birch_chest_boat)
	int(833):  1,  // Jungle Boat (jungle_boat)
	int(834):  1,  // Jungle Boat with Chest (jungle_chest_boat)
	int(835):  1,  // Acacia Boat (acacia_boat)
	int(836):  1,  // Acacia Boat with Chest (acacia_chest_boat)
	int(837):  1,  // Cherry Boat (cherry_boat)
	int(838):  1,  // Cherry Boat with Chest (cherry_chest_boat)
	int(839):  1,  // Dark Oak Boat (dark_oak_boat)
	int(840):  1,  // Dark Oak Boat with Chest (dark_oak_chest_boat)
	int(841):  1,  // Pale Oak Boat (pale_oak_boat)
	int(842):  1,  // Pale Oak Boat with Chest (pale_oak_chest_boat)
	int(843):  1,  // Mangrove Boat (mangrove_boat)
	int(844):  1,  // Mangrove Boat with Chest (mangrove_chest_boat)
	int(845):  1,  // Bamboo Raft (bamboo_raft)
	int(846):  1,  // Bamboo Raft with Chest (bamboo_chest_raft)
	int(851):  1,  // Turtle Shell (turtle_helmet)
	int(854):  1,  // Wolf Armor (wolf_armor)
	int(855):  1,  // Flint and Steel (flint_and_steel)
	int(858):  1,  // Bow (bow)
	int(875):  1,  // Wooden Sword (wooden_sword)
	int(876):  1,  // Wooden Shovel (wooden_shovel)
	int(877):  1,  // Wooden Pickaxe (wooden_pickaxe)
	int(878):  1,  // Wooden Axe (wooden_axe)
	int(879):  1,  // Wooden Hoe (wooden_hoe)
	int(880):  1,  // Stone Sword (stone_sword)
	int(881):  1,  // Stone Shovel (stone_shovel)
	int(882):  1,  // Stone Pickaxe (stone_pickaxe)
	int(883):  1,  // Stone Axe (stone_axe)
	int(884):  1,  // Stone Hoe (stone_hoe)
	int(885):  1,  // Golden Sword (golden_sword)
	int(886):  1,  // Golden Shovel (golden_shovel)
	int(887):  1,  // Golden Pickaxe (golden_pickaxe)
	int(888):  1,  // Golden Axe (golden_axe)
	int(889):  1,  // Golden Hoe (golden_hoe)
	int(890):  1,  // Iron Sword (iron_sword)
	int(891):  1,  // Iron Shovel (iron_shovel)
	int(892):  1,  // Iron Pickaxe (iron_pickaxe)
	int(893):  1,  // Iron Axe (iron_axe)
	int(894):  1,  // Iron Hoe (iron_hoe)
	int(895):  1,  // Diamond Sword (diamond_sword)
	int(896):  1,  // Diamond Shovel (diamond_shovel)
	int(897):  1,  // Diamond Pickaxe (diamond_pickaxe)
	int(898):  1,  // Diamond Axe (diamond_axe)
	int(899):  1,  // Diamond Hoe (diamond_hoe)
	int(900):  1,  // Netherite Sword (netherite_sword)
	int(901):  1,  // Netherite Shovel (netherite_shovel)
	int(902):  1,  // Netherite Pickaxe (netherite_pickaxe)
	int(903):  1,  // Netherite Axe (netherite_axe)
	int(904):  1,  // Netherite Hoe (netherite_hoe)
	int(906):  1,  // Mushroom Stew (mushroom_stew)
	int(913):  1,  // Leather Cap (leather_helmet)
	int(914):  1,  // Leather Tunic (leather_chestplate)
	int(915):  1,  // Leather Pants (leather_leggings)
	int(916):  1,  // Leather Boots (leather_boots)
	int(917):  1,  // Chainmail Helmet (chainmail_helmet)
	int(918):  1,  // Chainmail Chestplate (chainmail_chestplate)
	int(919):  1,  // Chainmail Leggings (chainmail_leggings)
	int(920):  1,  // Chainmail Boots (chainmail_boots)
	int(921):  1,  // Iron Helmet (iron_helmet)
	int(922):  1,  // Iron Chestplate (iron_chestplate)
	int(923):  1,  // Iron Leggings (iron_leggings)
	int(924):  1,  // Iron Boots (iron_boots)
	int(925):  1,  // Diamond Helmet (diamond_helmet)
	int(926):  1,  // Diamond Chestplate (diamond_chestplate)
	int(927):  1,  // Diamond Leggings (diamond_leggings)
	int(928):  1,  // Diamond Boots (diamond_boots)
	int(929):  1,  // Golden Helmet (golden_helmet)
	int(930):  1,  // Golden Chestplate (golden_chestplate)
	int(931):  1,  // Golden Leggings (golden_leggings)
	int(932):  1,  // Golden Boots (golden_boots)
	int(933):  1,  // Netherite Helmet (netherite_helmet)
	int(934):  1,  // Netherite Chestplate (netherite_chestplate)
	int(935):  1,  // Netherite Leggings (netherite_leggings)
	int(936):  1,  // Netherite Boots (netherite_boots)
	int(943):  16, // Oak Sign (oak_sign)
	int(944):  16, // Spruce Sign (spruce_sign)
	int(945):  16, // Birch Sign (birch_sign)
	int(946):  16, // Jungle Sign (jungle_sign)
	int(947):  16, // Acacia Sign (acacia_sign)
	int(948):  16, // Cherry Sign (cherry_sign)
	int(949):  16, // Dark Oak Sign (dark_oak_sign)
	int(950):  16, // Pale Oak Sign (pale_oak_sign)
	int(951):  16, // Mangrove Sign (mangrove_sign)
	int(952):  16, // Bamboo Sign (bamboo_sign)
	int(953):  16, // Crimson Sign (crimson_sign)
	int(954):  16, // Warped Sign (warped_sign)
	int(955):  16, // Oak Hanging Sign (oak_hanging_sign)
	int(956):  16, // Spruce Hanging Sign (spruce_hanging_sign)
	int(957):  16, // Birch Hanging Sign (birch_hanging_sign)
	int(958):  16, // Jungle Hanging Sign (jungle_hanging_sign)
	int(959):  16, // Acacia Hanging Sign (acacia_hanging_sign)
	int(960):  16, // Cherry Hanging Sign (cherry_hanging_sign)
	int(961):  16, // Dark Oak Hanging Sign (dark_oak_hanging_sign)
	int(962):  16, // Pale Oak Hanging Sign (pale_oak_hanging_sign)
	int(963):  16, // Mangrove Hanging Sign (mangrove_hanging_sign)
	int(964):  16, // Bamboo Hanging Sign (bamboo_hanging_sign)
	int(965):  16, // Crimson Hanging Sign (crimson_hanging_sign)
	int(966):  16, // Warped Hanging Sign (warped_hanging_sign)
	int(967):  16, // Bucket (bucket)
	int(968):  1,  // Water Bucket (water_bucket)
	int(969):  1,  // Lava Bucket (lava_bucket)
	int(970):  1,  // Powder Snow Bucket (powder_snow_bucket)
	int(971):  16, // Snowball (snowball)
	int(973):  1,  // Milk Bucket (milk_bucket)
	int(974):  1,  // Bucket of Pufferfish (pufferfish_bucket)
	int(975):  1,  // Bucket of Salmon (salmon_bucket)
	int(976):  1,  // Bucket of Cod (cod_bucket)
	int(977):  1,  // Bucket of Tropical Fish (tropical_fish_bucket)
	int(978):  1,  // Bucket of Axolotl (axolotl_bucket)
	int(979):  1,  // Bucket of Tadpole (tadpole_bucket)
	int(986):  16, // Egg (egg)
	int(987):  16, // Blue Egg (blue_egg)
	int(988):  16, // Brown Egg (brown_egg)
	int(991):  1,  // Bundle (bundle)
	int(992):  1,  // White Bundle (white_bundle)
	int(993):  1,  // Orange Bundle (orange_bundle)
	int(994):  1,  // Magenta Bundle (magenta_bundle)
	int(995):  1,  // Light Blue Bundle (light_blue_bundle)
	int(996):  1,  // Yellow Bundle (yellow_bundle)
	int(997):  1,  // Lime Bundle (lime_bundle)
	int(998):  1,  // Pink Bundle (pink_bundle)
	int(999):  1,  // Gray Bundle (gray_bundle)
	int(1000): 1,  // Light Gray Bundle (light_gray_bundle)
	int(1001): 1,  // Cyan Bundle (cyan_bundle)
	int(1002): 1,  // Purple Bundle (purple_bundle)
	int(1003): 1,  // Blue Bundle (blue_bundle)
	int(1004): 1,  // Brown Bundle (brown_bundle)
	int(1005): 1,  // Green Bundle (green_bundle)
	int(1006): 1,  // Red Bundle (red_bundle)
	int(1007): 1,  // Black Bundle (black_bundle)
	int(1008): 1,  // Fishing Rod (fishing_rod)
	int(1010): 1,  // Spyglass (spyglass)
	int(1040): 1,  // Cake (cake)
	int(1041): 1,  // White Bed (white_bed)
	int(1042): 1,  // Orange Bed (orange_bed)
	int(1043): 1,  // Magenta Bed (magenta_bed)
	int(1044): 1,  // Light Blue Bed (light_blue_bed)
	int(1045): 1,  // Yellow Bed (yellow_bed)
	int(1046): 1,  // Lime Bed (lime_bed)
	int(1047): 1,  // Pink Bed (pink_bed)
	int(1048): 1,  // Gray Bed (gray_bed)
	int(1049): 1,  // Light Gray Bed (light_gray_bed)
	int(1050): 1,  // Cyan Bed (cyan_bed)
	int(1051): 1,  // Purple Bed (purple_bed)
	int(1052): 1,  // Blue Bed (blue_bed)
	int(1053): 1,  // Brown Bed (brown_bed)
	int(1054): 1,  // Green Bed (green_bed)
	int(1055): 1,  // Red Bed (red_bed)
	int(1056): 1,  // Black Bed (black_bed)
	int(1060): 1,  // Shears (shears)
	int(1070): 16, // Ender Pearl (ender_pearl)
	int(1076): 1,  // Potion (potion)
	int(1170): 1,  // Book and Quill (writable_book)
	int(1171): 16, // Written Book (written_book)
	int(1173): 1,  // Mace (mace)
	int(1194): 1,  // Enchanted Book (enchanted_book)
	int(1201): 1,  // Rabbit Stew (rabbit_stew)
	int(1204): 16, // Armor Stand (armor_stand)
	int(1205): 1,  // Iron Horse Armor (iron_horse_armor)
	int(1206): 1,  // Golden Horse Armor (golden_horse_armor)
	int(1207): 1,  // Diamond Horse Armor (diamond_horse_armor)
	int(1208): 1,  // Leather Horse Armor (leather_horse_armor)
	int(1211): 1,  // Minecart with Command Block (command_block_minecart)
	int(1214): 16, // White Banner (white_banner)
	int(1215): 16, // Orange Banner (orange_banner)
	int(1216): 16, // Magenta Banner (magenta_banner)
	int(1217): 16, // Light Blue Banner (light_blue_banner)
	int(1218): 16, // Yellow Banner (yellow_banner)
	int(1219): 16, // Lime Banner (lime_banner)
	int(1220): 16, // Pink Banner (pink_banner)
	int(1221): 16, // Gray Banner (gray_banner)
	int(1222): 16, // Light Gray Banner (light_gray_banner)
	int(1223): 16, // Cyan Banner (cyan_banner)
	int(1224): 16, // Purple Banner (purple_banner)
	int(1225): 16, // Blue Banner (blue_banner)
	int(1226): 16, // Brown Banner (brown_banner)
	int(1227): 16, // Green Banner (green_banner)
	int(1228): 16, // Red Banner (red_banner)
	int(1229): 16, // Black Banner (black_banner)
	int(1237): 1,  // Beetroot Soup (beetroot_soup)
	int(1239): 1,  // Splash Potion (splash_potion)
	int(1242): 1,  // Lingering Potion (lingering_potion)
	int(1243): 1,  // Shield (shield)
	int(1244): 1,  // Totem of Undying (totem_of_undying)
	int(1247): 1,  // Knowledge Book (knowledge_book)
	int(1248): 1,  // Debug Stick (debug_stick)
	int(1249): 1,  // Music Disc (music_disc_13)
	int(1250): 1,  // Music Disc (music_disc_cat)
	int(1251): 1,  // Music Disc (music_disc_blocks)
	int(1252): 1,  // Music Disc (music_disc_chirp)
	int(1253): 1,  // Music Disc (music_disc_creator)
	int(1254): 1,  // Music Disc (music_disc_creator_music_box)
	int(1255): 1,  // Music Disc (music_disc_far)
	int(1256): 1,  // Music Disc (music_disc_lava_chicken)
	int(1257): 1,  // Music Disc (music_disc_mall)
	int(1258): 1,  // Music Disc (music_disc_mellohi)
	int(1259): 1,  // Music Disc (music_disc_stal)
	int(1260): 1,  // Music Disc (music_disc_strad)
	int(1261): 1,  // Music Disc (music_disc_ward)
	int(1262): 1,  // Music Disc (music_disc_11)
	int(1263): 1,  // Music Disc (music_disc_wait)
	int(1264): 1,  // Music Disc (music_disc_otherside)
	int(1265): 1,  // Music Disc (music_disc_relic)
	int(1266): 1,  // Music Disc (music_disc_5)
	int(1267): 1,  // Music Disc (music_disc_pigstep)
	int(1268): 1,  // Music Disc (music_disc_precipice)
	int(1269): 1,  // Music Disc (music_disc_tears)
	int(1271): 1,  // Trident (trident)
	int(1274): 1,  // Crossbow (crossbow)
	int(1275): 1,  // Suspicious Stew (suspicious_stew)
	int(1277): 1,  // Flower Charge Banner Pattern (flower_banner_pattern)
	int(1278): 1,  // Creeper Charge Banner Pattern (creeper_banner_pattern)
	int(1279): 1,  // Skull Charge Banner Pattern (skull_banner_pattern)
	int(1280): 1,  // Thing Banner Pattern (mojang_banner_pattern)
	int(1281): 1,  // Globe Banner Pattern (globe_banner_pattern)
	int(1282): 1,  // Snout Banner Pattern (piglin_banner_pattern)
	int(1283): 1,  // Flow Banner Pattern (flow_banner_pattern)
	int(1284): 1,  // Guster Banner Pattern (guster_banner_pattern)
	int(1285): 1,  // Field Masoned Banner Pattern (field_masoned_banner_pattern)
	int(1286): 1,  // Bordure Indented Banner Pattern (bordure_indented_banner_pattern)
	int(1287): 1,  // Goat Horn (goat_horn)
	int(1308): 16, // Honey Bottle (honey_bottle)
	int(1352): 1,  // Brush (brush)
}

// ItemDurabilityTable stores max durability for items.
var ItemDurabilityTable = map[int]int{
	int(823):  25,   // Carrot on a Stick (carrot_on_a_stick)
	int(824):  100,  // Warped Fungus on a Stick (warped_fungus_on_a_stick)
	int(826):  432,  // Elytra (elytra)
	int(851):  275,  // Turtle Shell (turtle_helmet)
	int(854):  64,   // Wolf Armor (wolf_armor)
	int(855):  64,   // Flint and Steel (flint_and_steel)
	int(858):  384,  // Bow (bow)
	int(875):  59,   // Wooden Sword (wooden_sword)
	int(876):  59,   // Wooden Shovel (wooden_shovel)
	int(877):  59,   // Wooden Pickaxe (wooden_pickaxe)
	int(878):  59,   // Wooden Axe (wooden_axe)
	int(879):  59,   // Wooden Hoe (wooden_hoe)
	int(880):  131,  // Stone Sword (stone_sword)
	int(881):  131,  // Stone Shovel (stone_shovel)
	int(882):  131,  // Stone Pickaxe (stone_pickaxe)
	int(883):  131,  // Stone Axe (stone_axe)
	int(884):  131,  // Stone Hoe (stone_hoe)
	int(885):  32,   // Golden Sword (golden_sword)
	int(886):  32,   // Golden Shovel (golden_shovel)
	int(887):  32,   // Golden Pickaxe (golden_pickaxe)
	int(888):  32,   // Golden Axe (golden_axe)
	int(889):  32,   // Golden Hoe (golden_hoe)
	int(890):  250,  // Iron Sword (iron_sword)
	int(891):  250,  // Iron Shovel (iron_shovel)
	int(892):  250,  // Iron Pickaxe (iron_pickaxe)
	int(893):  250,  // Iron Axe (iron_axe)
	int(894):  250,  // Iron Hoe (iron_hoe)
	int(895):  1561, // Diamond Sword (diamond_sword)
	int(896):  1561, // Diamond Shovel (diamond_shovel)
	int(897):  1561, // Diamond Pickaxe (diamond_pickaxe)
	int(898):  1561, // Diamond Axe (diamond_axe)
	int(899):  1561, // Diamond Hoe (diamond_hoe)
	int(900):  2031, // Netherite Sword (netherite_sword)
	int(901):  2031, // Netherite Shovel (netherite_shovel)
	int(902):  2031, // Netherite Pickaxe (netherite_pickaxe)
	int(903):  2031, // Netherite Axe (netherite_axe)
	int(904):  2031, // Netherite Hoe (netherite_hoe)
	int(913):  55,   // Leather Cap (leather_helmet)
	int(914):  80,   // Leather Tunic (leather_chestplate)
	int(915):  75,   // Leather Pants (leather_leggings)
	int(916):  65,   // Leather Boots (leather_boots)
	int(917):  165,  // Chainmail Helmet (chainmail_helmet)
	int(918):  240,  // Chainmail Chestplate (chainmail_chestplate)
	int(919):  225,  // Chainmail Leggings (chainmail_leggings)
	int(920):  195,  // Chainmail Boots (chainmail_boots)
	int(921):  165,  // Iron Helmet (iron_helmet)
	int(922):  240,  // Iron Chestplate (iron_chestplate)
	int(923):  225,  // Iron Leggings (iron_leggings)
	int(924):  195,  // Iron Boots (iron_boots)
	int(925):  363,  // Diamond Helmet (diamond_helmet)
	int(926):  528,  // Diamond Chestplate (diamond_chestplate)
	int(927):  495,  // Diamond Leggings (diamond_leggings)
	int(928):  429,  // Diamond Boots (diamond_boots)
	int(929):  77,   // Golden Helmet (golden_helmet)
	int(930):  112,  // Golden Chestplate (golden_chestplate)
	int(931):  105,  // Golden Leggings (golden_leggings)
	int(932):  91,   // Golden Boots (golden_boots)
	int(933):  407,  // Netherite Helmet (netherite_helmet)
	int(934):  592,  // Netherite Chestplate (netherite_chestplate)
	int(935):  555,  // Netherite Leggings (netherite_leggings)
	int(936):  481,  // Netherite Boots (netherite_boots)
	int(1008): 64,   // Fishing Rod (fishing_rod)
	int(1060): 238,  // Shears (shears)
	int(1173): 500,  // Mace (mace)
	int(1243): 336,  // Shield (shield)
	int(1271): 250,  // Trident (trident)
	int(1274): 465,  // Crossbow (crossbow)
	int(1352): 64,   // Brush (brush)
}

// GetMaxStackSize returns the max stack size for an item.
func GetMaxStackSize(id int) int {
	if size, ok := MaxStackSizeTable[id]; ok {
		return size
	}
	return 64
}

// GetMaxDurability returns the max durability for an item, 0 if none.
func GetMaxDurability(id int) int {
	if dur, ok := ItemDurabilityTable[id]; ok {
		return dur
	}
	return 0
}

// ItemNameToID maps item names to IDs.
var ItemNameToID = map[string]int{
	"air":                                    int(0),
	"stone":                                  int(1),
	"granite":                                int(2),
	"polished_granite":                       int(3),
	"diorite":                                int(4),
	"polished_diorite":                       int(5),
	"andesite":                               int(6),
	"polished_andesite":                      int(7),
	"deepslate":                              int(8),
	"cobbled_deepslate":                      int(9),
	"polished_deepslate":                     int(10),
	"calcite":                                int(11),
	"tuff":                                   int(12),
	"tuff_slab":                              int(13),
	"tuff_stairs":                            int(14),
	"tuff_wall":                              int(15),
	"chiseled_tuff":                          int(16),
	"polished_tuff":                          int(17),
	"polished_tuff_slab":                     int(18),
	"polished_tuff_stairs":                   int(19),
	"polished_tuff_wall":                     int(20),
	"tuff_bricks":                            int(21),
	"tuff_brick_slab":                        int(22),
	"tuff_brick_stairs":                      int(23),
	"tuff_brick_wall":                        int(24),
	"chiseled_tuff_bricks":                   int(25),
	"dripstone_block":                        int(26),
	"grass_block":                            int(27),
	"dirt":                                   int(28),
	"coarse_dirt":                            int(29),
	"podzol":                                 int(30),
	"rooted_dirt":                            int(31),
	"mud":                                    int(32),
	"crimson_nylium":                         int(33),
	"warped_nylium":                          int(34),
	"cobblestone":                            int(35),
	"oak_planks":                             int(36),
	"spruce_planks":                          int(37),
	"birch_planks":                           int(38),
	"jungle_planks":                          int(39),
	"acacia_planks":                          int(40),
	"cherry_planks":                          int(41),
	"dark_oak_planks":                        int(42),
	"pale_oak_planks":                        int(43),
	"mangrove_planks":                        int(44),
	"bamboo_planks":                          int(45),
	"crimson_planks":                         int(46),
	"warped_planks":                          int(47),
	"bamboo_mosaic":                          int(48),
	"oak_sapling":                            int(49),
	"spruce_sapling":                         int(50),
	"birch_sapling":                          int(51),
	"jungle_sapling":                         int(52),
	"acacia_sapling":                         int(53),
	"cherry_sapling":                         int(54),
	"dark_oak_sapling":                       int(55),
	"pale_oak_sapling":                       int(56),
	"mangrove_propagule":                     int(57),
	"bedrock":                                int(58),
	"sand":                                   int(59),
	"suspicious_sand":                        int(60),
	"suspicious_gravel":                      int(61),
	"red_sand":                               int(62),
	"gravel":                                 int(63),
	"coal_ore":                               int(64),
	"deepslate_coal_ore":                     int(65),
	"iron_ore":                               int(66),
	"deepslate_iron_ore":                     int(67),
	"copper_ore":                             int(68),
	"deepslate_copper_ore":                   int(69),
	"gold_ore":                               int(70),
	"deepslate_gold_ore":                     int(71),
	"redstone_ore":                           int(72),
	"deepslate_redstone_ore":                 int(73),
	"emerald_ore":                            int(74),
	"deepslate_emerald_ore":                  int(75),
	"lapis_ore":                              int(76),
	"deepslate_lapis_ore":                    int(77),
	"diamond_ore":                            int(78),
	"deepslate_diamond_ore":                  int(79),
	"nether_gold_ore":                        int(80),
	"nether_quartz_ore":                      int(81),
	"ancient_debris":                         int(82),
	"coal_block":                             int(83),
	"raw_iron_block":                         int(84),
	"raw_copper_block":                       int(85),
	"raw_gold_block":                         int(86),
	"heavy_core":                             int(87),
	"amethyst_block":                         int(88),
	"budding_amethyst":                       int(89),
	"iron_block":                             int(90),
	"copper_block":                           int(91),
	"gold_block":                             int(92),
	"diamond_block":                          int(93),
	"netherite_block":                        int(94),
	"exposed_copper":                         int(95),
	"weathered_copper":                       int(96),
	"oxidized_copper":                        int(97),
	"chiseled_copper":                        int(98),
	"exposed_chiseled_copper":                int(99),
	"weathered_chiseled_copper":              int(100),
	"oxidized_chiseled_copper":               int(101),
	"cut_copper":                             int(102),
	"exposed_cut_copper":                     int(103),
	"weathered_cut_copper":                   int(104),
	"oxidized_cut_copper":                    int(105),
	"cut_copper_stairs":                      int(106),
	"exposed_cut_copper_stairs":              int(107),
	"weathered_cut_copper_stairs":            int(108),
	"oxidized_cut_copper_stairs":             int(109),
	"cut_copper_slab":                        int(110),
	"exposed_cut_copper_slab":                int(111),
	"weathered_cut_copper_slab":              int(112),
	"oxidized_cut_copper_slab":               int(113),
	"waxed_copper_block":                     int(114),
	"waxed_exposed_copper":                   int(115),
	"waxed_weathered_copper":                 int(116),
	"waxed_oxidized_copper":                  int(117),
	"waxed_chiseled_copper":                  int(118),
	"waxed_exposed_chiseled_copper":          int(119),
	"waxed_weathered_chiseled_copper":        int(120),
	"waxed_oxidized_chiseled_copper":         int(121),
	"waxed_cut_copper":                       int(122),
	"waxed_exposed_cut_copper":               int(123),
	"waxed_weathered_cut_copper":             int(124),
	"waxed_oxidized_cut_copper":              int(125),
	"waxed_cut_copper_stairs":                int(126),
	"waxed_exposed_cut_copper_stairs":        int(127),
	"waxed_weathered_cut_copper_stairs":      int(128),
	"waxed_oxidized_cut_copper_stairs":       int(129),
	"waxed_cut_copper_slab":                  int(130),
	"waxed_exposed_cut_copper_slab":          int(131),
	"waxed_weathered_cut_copper_slab":        int(132),
	"waxed_oxidized_cut_copper_slab":         int(133),
	"oak_log":                                int(134),
	"spruce_log":                             int(135),
	"birch_log":                              int(136),
	"jungle_log":                             int(137),
	"acacia_log":                             int(138),
	"cherry_log":                             int(139),
	"pale_oak_log":                           int(140),
	"dark_oak_log":                           int(141),
	"mangrove_log":                           int(142),
	"mangrove_roots":                         int(143),
	"muddy_mangrove_roots":                   int(144),
	"crimson_stem":                           int(145),
	"warped_stem":                            int(146),
	"bamboo_block":                           int(147),
	"stripped_oak_log":                       int(148),
	"stripped_spruce_log":                    int(149),
	"stripped_birch_log":                     int(150),
	"stripped_jungle_log":                    int(151),
	"stripped_acacia_log":                    int(152),
	"stripped_cherry_log":                    int(153),
	"stripped_dark_oak_log":                  int(154),
	"stripped_pale_oak_log":                  int(155),
	"stripped_mangrove_log":                  int(156),
	"stripped_crimson_stem":                  int(157),
	"stripped_warped_stem":                   int(158),
	"stripped_oak_wood":                      int(159),
	"stripped_spruce_wood":                   int(160),
	"stripped_birch_wood":                    int(161),
	"stripped_jungle_wood":                   int(162),
	"stripped_acacia_wood":                   int(163),
	"stripped_cherry_wood":                   int(164),
	"stripped_dark_oak_wood":                 int(165),
	"stripped_pale_oak_wood":                 int(166),
	"stripped_mangrove_wood":                 int(167),
	"stripped_crimson_hyphae":                int(168),
	"stripped_warped_hyphae":                 int(169),
	"stripped_bamboo_block":                  int(170),
	"oak_wood":                               int(171),
	"spruce_wood":                            int(172),
	"birch_wood":                             int(173),
	"jungle_wood":                            int(174),
	"acacia_wood":                            int(175),
	"cherry_wood":                            int(176),
	"pale_oak_wood":                          int(177),
	"dark_oak_wood":                          int(178),
	"mangrove_wood":                          int(179),
	"crimson_hyphae":                         int(180),
	"warped_hyphae":                          int(181),
	"oak_leaves":                             int(182),
	"spruce_leaves":                          int(183),
	"birch_leaves":                           int(184),
	"jungle_leaves":                          int(185),
	"acacia_leaves":                          int(186),
	"cherry_leaves":                          int(187),
	"dark_oak_leaves":                        int(188),
	"pale_oak_leaves":                        int(189),
	"mangrove_leaves":                        int(190),
	"azalea_leaves":                          int(191),
	"flowering_azalea_leaves":                int(192),
	"sponge":                                 int(193),
	"wet_sponge":                             int(194),
	"glass":                                  int(195),
	"tinted_glass":                           int(196),
	"lapis_block":                            int(197),
	"sandstone":                              int(198),
	"chiseled_sandstone":                     int(199),
	"cut_sandstone":                          int(200),
	"cobweb":                                 int(201),
	"short_grass":                            int(202),
	"fern":                                   int(203),
	"bush":                                   int(204),
	"azalea":                                 int(205),
	"flowering_azalea":                       int(206),
	"dead_bush":                              int(207),
	"firefly_bush":                           int(208),
	"short_dry_grass":                        int(209),
	"tall_dry_grass":                         int(210),
	"seagrass":                               int(211),
	"sea_pickle":                             int(212),
	"white_wool":                             int(213),
	"orange_wool":                            int(214),
	"magenta_wool":                           int(215),
	"light_blue_wool":                        int(216),
	"yellow_wool":                            int(217),
	"lime_wool":                              int(218),
	"pink_wool":                              int(219),
	"gray_wool":                              int(220),
	"light_gray_wool":                        int(221),
	"cyan_wool":                              int(222),
	"purple_wool":                            int(223),
	"blue_wool":                              int(224),
	"brown_wool":                             int(225),
	"green_wool":                             int(226),
	"red_wool":                               int(227),
	"black_wool":                             int(228),
	"dandelion":                              int(229),
	"open_eyeblossom":                        int(230),
	"closed_eyeblossom":                      int(231),
	"poppy":                                  int(232),
	"blue_orchid":                            int(233),
	"allium":                                 int(234),
	"azure_bluet":                            int(235),
	"red_tulip":                              int(236),
	"orange_tulip":                           int(237),
	"white_tulip":                            int(238),
	"pink_tulip":                             int(239),
	"oxeye_daisy":                            int(240),
	"cornflower":                             int(241),
	"lily_of_the_valley":                     int(242),
	"wither_rose":                            int(243),
	"torchflower":                            int(244),
	"pitcher_plant":                          int(245),
	"spore_blossom":                          int(246),
	"brown_mushroom":                         int(247),
	"red_mushroom":                           int(248),
	"crimson_fungus":                         int(249),
	"warped_fungus":                          int(250),
	"crimson_roots":                          int(251),
	"warped_roots":                           int(252),
	"nether_sprouts":                         int(253),
	"weeping_vines":                          int(254),
	"twisting_vines":                         int(255),
	"sugar_cane":                             int(256),
	"kelp":                                   int(257),
	"pink_petals":                            int(258),
	"wildflowers":                            int(259),
	"leaf_litter":                            int(260),
	"moss_carpet":                            int(261),
	"moss_block":                             int(262),
	"pale_moss_carpet":                       int(263),
	"pale_hanging_moss":                      int(264),
	"pale_moss_block":                        int(265),
	"hanging_roots":                          int(266),
	"big_dripleaf":                           int(267),
	"small_dripleaf":                         int(268),
	"bamboo":                                 int(269),
	"oak_slab":                               int(270),
	"spruce_slab":                            int(271),
	"birch_slab":                             int(272),
	"jungle_slab":                            int(273),
	"acacia_slab":                            int(274),
	"cherry_slab":                            int(275),
	"dark_oak_slab":                          int(276),
	"pale_oak_slab":                          int(277),
	"mangrove_slab":                          int(278),
	"bamboo_slab":                            int(279),
	"bamboo_mosaic_slab":                     int(280),
	"crimson_slab":                           int(281),
	"warped_slab":                            int(282),
	"stone_slab":                             int(283),
	"smooth_stone_slab":                      int(284),
	"sandstone_slab":                         int(285),
	"cut_sandstone_slab":                     int(286),
	"petrified_oak_slab":                     int(287),
	"cobblestone_slab":                       int(288),
	"brick_slab":                             int(289),
	"stone_brick_slab":                       int(290),
	"mud_brick_slab":                         int(291),
	"nether_brick_slab":                      int(292),
	"quartz_slab":                            int(293),
	"red_sandstone_slab":                     int(294),
	"cut_red_sandstone_slab":                 int(295),
	"purpur_slab":                            int(296),
	"prismarine_slab":                        int(297),
	"prismarine_brick_slab":                  int(298),
	"dark_prismarine_slab":                   int(299),
	"smooth_quartz":                          int(300),
	"smooth_red_sandstone":                   int(301),
	"smooth_sandstone":                       int(302),
	"smooth_stone":                           int(303),
	"bricks":                                 int(304),
	"bookshelf":                              int(305),
	"chiseled_bookshelf":                     int(306),
	"decorated_pot":                          int(307),
	"mossy_cobblestone":                      int(308),
	"obsidian":                               int(309),
	"torch":                                  int(310),
	"end_rod":                                int(311),
	"chorus_plant":                           int(312),
	"chorus_flower":                          int(313),
	"purpur_block":                           int(314),
	"purpur_pillar":                          int(315),
	"purpur_stairs":                          int(316),
	"spawner":                                int(317),
	"creaking_heart":                         int(318),
	"chest":                                  int(319),
	"crafting_table":                         int(320),
	"farmland":                               int(321),
	"furnace":                                int(322),
	"ladder":                                 int(323),
	"cobblestone_stairs":                     int(324),
	"snow":                                   int(325),
	"ice":                                    int(326),
	"snow_block":                             int(327),
	"cactus":                                 int(328),
	"cactus_flower":                          int(329),
	"clay":                                   int(330),
	"jukebox":                                int(331),
	"oak_fence":                              int(332),
	"spruce_fence":                           int(333),
	"birch_fence":                            int(334),
	"jungle_fence":                           int(335),
	"acacia_fence":                           int(336),
	"cherry_fence":                           int(337),
	"dark_oak_fence":                         int(338),
	"pale_oak_fence":                         int(339),
	"mangrove_fence":                         int(340),
	"bamboo_fence":                           int(341),
	"crimson_fence":                          int(342),
	"warped_fence":                           int(343),
	"pumpkin":                                int(344),
	"carved_pumpkin":                         int(345),
	"jack_o_lantern":                         int(346),
	"netherrack":                             int(347),
	"soul_sand":                              int(348),
	"soul_soil":                              int(349),
	"basalt":                                 int(350),
	"polished_basalt":                        int(351),
	"smooth_basalt":                          int(352),
	"soul_torch":                             int(353),
	"glowstone":                              int(354),
	"infested_stone":                         int(355),
	"infested_cobblestone":                   int(356),
	"infested_stone_bricks":                  int(357),
	"infested_mossy_stone_bricks":            int(358),
	"infested_cracked_stone_bricks":          int(359),
	"infested_chiseled_stone_bricks":         int(360),
	"infested_deepslate":                     int(361),
	"stone_bricks":                           int(362),
	"mossy_stone_bricks":                     int(363),
	"cracked_stone_bricks":                   int(364),
	"chiseled_stone_bricks":                  int(365),
	"packed_mud":                             int(366),
	"mud_bricks":                             int(367),
	"deepslate_bricks":                       int(368),
	"cracked_deepslate_bricks":               int(369),
	"deepslate_tiles":                        int(370),
	"cracked_deepslate_tiles":                int(371),
	"chiseled_deepslate":                     int(372),
	"reinforced_deepslate":                   int(373),
	"brown_mushroom_block":                   int(374),
	"red_mushroom_block":                     int(375),
	"mushroom_stem":                          int(376),
	"iron_bars":                              int(377),
	"chain":                                  int(378),
	"glass_pane":                             int(379),
	"melon":                                  int(380),
	"vine":                                   int(381),
	"glow_lichen":                            int(382),
	"resin_clump":                            int(383),
	"resin_block":                            int(384),
	"resin_bricks":                           int(385),
	"resin_brick_stairs":                     int(386),
	"resin_brick_slab":                       int(387),
	"resin_brick_wall":                       int(388),
	"chiseled_resin_bricks":                  int(389),
	"brick_stairs":                           int(390),
	"stone_brick_stairs":                     int(391),
	"mud_brick_stairs":                       int(392),
	"mycelium":                               int(393),
	"lily_pad":                               int(394),
	"nether_bricks":                          int(395),
	"cracked_nether_bricks":                  int(396),
	"chiseled_nether_bricks":                 int(397),
	"nether_brick_fence":                     int(398),
	"nether_brick_stairs":                    int(399),
	"sculk":                                  int(400),
	"sculk_vein":                             int(401),
	"sculk_catalyst":                         int(402),
	"sculk_shrieker":                         int(403),
	"enchanting_table":                       int(404),
	"end_portal_frame":                       int(405),
	"end_stone":                              int(406),
	"end_stone_bricks":                       int(407),
	"dragon_egg":                             int(408),
	"sandstone_stairs":                       int(409),
	"ender_chest":                            int(410),
	"emerald_block":                          int(411),
	"oak_stairs":                             int(412),
	"spruce_stairs":                          int(413),
	"birch_stairs":                           int(414),
	"jungle_stairs":                          int(415),
	"acacia_stairs":                          int(416),
	"cherry_stairs":                          int(417),
	"dark_oak_stairs":                        int(418),
	"pale_oak_stairs":                        int(419),
	"mangrove_stairs":                        int(420),
	"bamboo_stairs":                          int(421),
	"bamboo_mosaic_stairs":                   int(422),
	"crimson_stairs":                         int(423),
	"warped_stairs":                          int(424),
	"command_block":                          int(425),
	"beacon":                                 int(426),
	"cobblestone_wall":                       int(427),
	"mossy_cobblestone_wall":                 int(428),
	"brick_wall":                             int(429),
	"prismarine_wall":                        int(430),
	"red_sandstone_wall":                     int(431),
	"mossy_stone_brick_wall":                 int(432),
	"granite_wall":                           int(433),
	"stone_brick_wall":                       int(434),
	"mud_brick_wall":                         int(435),
	"nether_brick_wall":                      int(436),
	"andesite_wall":                          int(437),
	"red_nether_brick_wall":                  int(438),
	"sandstone_wall":                         int(439),
	"end_stone_brick_wall":                   int(440),
	"diorite_wall":                           int(441),
	"blackstone_wall":                        int(442),
	"polished_blackstone_wall":               int(443),
	"polished_blackstone_brick_wall":         int(444),
	"cobbled_deepslate_wall":                 int(445),
	"polished_deepslate_wall":                int(446),
	"deepslate_brick_wall":                   int(447),
	"deepslate_tile_wall":                    int(448),
	"anvil":                                  int(449),
	"chipped_anvil":                          int(450),
	"damaged_anvil":                          int(451),
	"chiseled_quartz_block":                  int(452),
	"quartz_block":                           int(453),
	"quartz_bricks":                          int(454),
	"quartz_pillar":                          int(455),
	"quartz_stairs":                          int(456),
	"white_terracotta":                       int(457),
	"orange_terracotta":                      int(458),
	"magenta_terracotta":                     int(459),
	"light_blue_terracotta":                  int(460),
	"yellow_terracotta":                      int(461),
	"lime_terracotta":                        int(462),
	"pink_terracotta":                        int(463),
	"gray_terracotta":                        int(464),
	"light_gray_terracotta":                  int(465),
	"cyan_terracotta":                        int(466),
	"purple_terracotta":                      int(467),
	"blue_terracotta":                        int(468),
	"brown_terracotta":                       int(469),
	"green_terracotta":                       int(470),
	"red_terracotta":                         int(471),
	"black_terracotta":                       int(472),
	"barrier":                                int(473),
	"light":                                  int(474),
	"hay_block":                              int(475),
	"white_carpet":                           int(476),
	"orange_carpet":                          int(477),
	"magenta_carpet":                         int(478),
	"light_blue_carpet":                      int(479),
	"yellow_carpet":                          int(480),
	"lime_carpet":                            int(481),
	"pink_carpet":                            int(482),
	"gray_carpet":                            int(483),
	"light_gray_carpet":                      int(484),
	"cyan_carpet":                            int(485),
	"purple_carpet":                          int(486),
	"blue_carpet":                            int(487),
	"brown_carpet":                           int(488),
	"green_carpet":                           int(489),
	"red_carpet":                             int(490),
	"black_carpet":                           int(491),
	"terracotta":                             int(492),
	"packed_ice":                             int(493),
	"dirt_path":                              int(494),
	"sunflower":                              int(495),
	"lilac":                                  int(496),
	"rose_bush":                              int(497),
	"peony":                                  int(498),
	"tall_grass":                             int(499),
	"large_fern":                             int(500),
	"white_stained_glass":                    int(501),
	"orange_stained_glass":                   int(502),
	"magenta_stained_glass":                  int(503),
	"light_blue_stained_glass":               int(504),
	"yellow_stained_glass":                   int(505),
	"lime_stained_glass":                     int(506),
	"pink_stained_glass":                     int(507),
	"gray_stained_glass":                     int(508),
	"light_gray_stained_glass":               int(509),
	"cyan_stained_glass":                     int(510),
	"purple_stained_glass":                   int(511),
	"blue_stained_glass":                     int(512),
	"brown_stained_glass":                    int(513),
	"green_stained_glass":                    int(514),
	"red_stained_glass":                      int(515),
	"black_stained_glass":                    int(516),
	"white_stained_glass_pane":               int(517),
	"orange_stained_glass_pane":              int(518),
	"magenta_stained_glass_pane":             int(519),
	"light_blue_stained_glass_pane":          int(520),
	"yellow_stained_glass_pane":              int(521),
	"lime_stained_glass_pane":                int(522),
	"pink_stained_glass_pane":                int(523),
	"gray_stained_glass_pane":                int(524),
	"light_gray_stained_glass_pane":          int(525),
	"cyan_stained_glass_pane":                int(526),
	"purple_stained_glass_pane":              int(527),
	"blue_stained_glass_pane":                int(528),
	"brown_stained_glass_pane":               int(529),
	"green_stained_glass_pane":               int(530),
	"red_stained_glass_pane":                 int(531),
	"black_stained_glass_pane":               int(532),
	"prismarine":                             int(533),
	"prismarine_bricks":                      int(534),
	"dark_prismarine":                        int(535),
	"prismarine_stairs":                      int(536),
	"prismarine_brick_stairs":                int(537),
	"dark_prismarine_stairs":                 int(538),
	"sea_lantern":                            int(539),
	"red_sandstone":                          int(540),
	"chiseled_red_sandstone":                 int(541),
	"cut_red_sandstone":                      int(542),
	"red_sandstone_stairs":                   int(543),
	"repeating_command_block":                int(544),
	"chain_command_block":                    int(545),
	"magma_block":                            int(546),
	"nether_wart_block":                      int(547),
	"warped_wart_block":                      int(548),
	"red_nether_bricks":                      int(549),
	"bone_block":                             int(550),
	"structure_void":                         int(551),
	"shulker_box":                            int(552),
	"white_shulker_box":                      int(553),
	"orange_shulker_box":                     int(554),
	"magenta_shulker_box":                    int(555),
	"light_blue_shulker_box":                 int(556),
	"yellow_shulker_box":                     int(557),
	"lime_shulker_box":                       int(558),
	"pink_shulker_box":                       int(559),
	"gray_shulker_box":                       int(560),
	"light_gray_shulker_box":                 int(561),
	"cyan_shulker_box":                       int(562),
	"purple_shulker_box":                     int(563),
	"blue_shulker_box":                       int(564),
	"brown_shulker_box":                      int(565),
	"green_shulker_box":                      int(566),
	"red_shulker_box":                        int(567),
	"black_shulker_box":                      int(568),
	"white_glazed_terracotta":                int(569),
	"orange_glazed_terracotta":               int(570),
	"magenta_glazed_terracotta":              int(571),
	"light_blue_glazed_terracotta":           int(572),
	"yellow_glazed_terracotta":               int(573),
	"lime_glazed_terracotta":                 int(574),
	"pink_glazed_terracotta":                 int(575),
	"gray_glazed_terracotta":                 int(576),
	"light_gray_glazed_terracotta":           int(577),
	"cyan_glazed_terracotta":                 int(578),
	"purple_glazed_terracotta":               int(579),
	"blue_glazed_terracotta":                 int(580),
	"brown_glazed_terracotta":                int(581),
	"green_glazed_terracotta":                int(582),
	"red_glazed_terracotta":                  int(583),
	"black_glazed_terracotta":                int(584),
	"white_concrete":                         int(585),
	"orange_concrete":                        int(586),
	"magenta_concrete":                       int(587),
	"light_blue_concrete":                    int(588),
	"yellow_concrete":                        int(589),
	"lime_concrete":                          int(590),
	"pink_concrete":                          int(591),
	"gray_concrete":                          int(592),
	"light_gray_concrete":                    int(593),
	"cyan_concrete":                          int(594),
	"purple_concrete":                        int(595),
	"blue_concrete":                          int(596),
	"brown_concrete":                         int(597),
	"green_concrete":                         int(598),
	"red_concrete":                           int(599),
	"black_concrete":                         int(600),
	"white_concrete_powder":                  int(601),
	"orange_concrete_powder":                 int(602),
	"magenta_concrete_powder":                int(603),
	"light_blue_concrete_powder":             int(604),
	"yellow_concrete_powder":                 int(605),
	"lime_concrete_powder":                   int(606),
	"pink_concrete_powder":                   int(607),
	"gray_concrete_powder":                   int(608),
	"light_gray_concrete_powder":             int(609),
	"cyan_concrete_powder":                   int(610),
	"purple_concrete_powder":                 int(611),
	"blue_concrete_powder":                   int(612),
	"brown_concrete_powder":                  int(613),
	"green_concrete_powder":                  int(614),
	"red_concrete_powder":                    int(615),
	"black_concrete_powder":                  int(616),
	"turtle_egg":                             int(617),
	"sniffer_egg":                            int(618),
	"dried_ghast":                            int(619),
	"dead_tube_coral_block":                  int(620),
	"dead_brain_coral_block":                 int(621),
	"dead_bubble_coral_block":                int(622),
	"dead_fire_coral_block":                  int(623),
	"dead_horn_coral_block":                  int(624),
	"tube_coral_block":                       int(625),
	"brain_coral_block":                      int(626),
	"bubble_coral_block":                     int(627),
	"fire_coral_block":                       int(628),
	"horn_coral_block":                       int(629),
	"tube_coral":                             int(630),
	"brain_coral":                            int(631),
	"bubble_coral":                           int(632),
	"fire_coral":                             int(633),
	"horn_coral":                             int(634),
	"dead_brain_coral":                       int(635),
	"dead_bubble_coral":                      int(636),
	"dead_fire_coral":                        int(637),
	"dead_horn_coral":                        int(638),
	"dead_tube_coral":                        int(639),
	"tube_coral_fan":                         int(640),
	"brain_coral_fan":                        int(641),
	"bubble_coral_fan":                       int(642),
	"fire_coral_fan":                         int(643),
	"horn_coral_fan":                         int(644),
	"dead_tube_coral_fan":                    int(645),
	"dead_brain_coral_fan":                   int(646),
	"dead_bubble_coral_fan":                  int(647),
	"dead_fire_coral_fan":                    int(648),
	"dead_horn_coral_fan":                    int(649),
	"blue_ice":                               int(650),
	"conduit":                                int(651),
	"polished_granite_stairs":                int(652),
	"smooth_red_sandstone_stairs":            int(653),
	"mossy_stone_brick_stairs":               int(654),
	"polished_diorite_stairs":                int(655),
	"mossy_cobblestone_stairs":               int(656),
	"end_stone_brick_stairs":                 int(657),
	"stone_stairs":                           int(658),
	"smooth_sandstone_stairs":                int(659),
	"smooth_quartz_stairs":                   int(660),
	"granite_stairs":                         int(661),
	"andesite_stairs":                        int(662),
	"red_nether_brick_stairs":                int(663),
	"polished_andesite_stairs":               int(664),
	"diorite_stairs":                         int(665),
	"cobbled_deepslate_stairs":               int(666),
	"polished_deepslate_stairs":              int(667),
	"deepslate_brick_stairs":                 int(668),
	"deepslate_tile_stairs":                  int(669),
	"polished_granite_slab":                  int(670),
	"smooth_red_sandstone_slab":              int(671),
	"mossy_stone_brick_slab":                 int(672),
	"polished_diorite_slab":                  int(673),
	"mossy_cobblestone_slab":                 int(674),
	"end_stone_brick_slab":                   int(675),
	"smooth_sandstone_slab":                  int(676),
	"smooth_quartz_slab":                     int(677),
	"granite_slab":                           int(678),
	"andesite_slab":                          int(679),
	"red_nether_brick_slab":                  int(680),
	"polished_andesite_slab":                 int(681),
	"diorite_slab":                           int(682),
	"cobbled_deepslate_slab":                 int(683),
	"polished_deepslate_slab":                int(684),
	"deepslate_brick_slab":                   int(685),
	"deepslate_tile_slab":                    int(686),
	"scaffolding":                            int(687),
	"redstone":                               int(688),
	"redstone_torch":                         int(689),
	"redstone_block":                         int(690),
	"repeater":                               int(691),
	"comparator":                             int(692),
	"piston":                                 int(693),
	"sticky_piston":                          int(694),
	"slime_block":                            int(695),
	"honey_block":                            int(696),
	"observer":                               int(697),
	"hopper":                                 int(698),
	"dispenser":                              int(699),
	"dropper":                                int(700),
	"lectern":                                int(701),
	"target":                                 int(702),
	"lever":                                  int(703),
	"lightning_rod":                          int(704),
	"daylight_detector":                      int(705),
	"sculk_sensor":                           int(706),
	"calibrated_sculk_sensor":                int(707),
	"tripwire_hook":                          int(708),
	"trapped_chest":                          int(709),
	"tnt":                                    int(710),
	"redstone_lamp":                          int(711),
	"note_block":                             int(712),
	"stone_button":                           int(713),
	"polished_blackstone_button":             int(714),
	"oak_button":                             int(715),
	"spruce_button":                          int(716),
	"birch_button":                           int(717),
	"jungle_button":                          int(718),
	"acacia_button":                          int(719),
	"cherry_button":                          int(720),
	"dark_oak_button":                        int(721),
	"pale_oak_button":                        int(722),
	"mangrove_button":                        int(723),
	"bamboo_button":                          int(724),
	"crimson_button":                         int(725),
	"warped_button":                          int(726),
	"stone_pressure_plate":                   int(727),
	"polished_blackstone_pressure_plate":     int(728),
	"light_weighted_pressure_plate":          int(729),
	"heavy_weighted_pressure_plate":          int(730),
	"oak_pressure_plate":                     int(731),
	"spruce_pressure_plate":                  int(732),
	"birch_pressure_plate":                   int(733),
	"jungle_pressure_plate":                  int(734),
	"acacia_pressure_plate":                  int(735),
	"cherry_pressure_plate":                  int(736),
	"dark_oak_pressure_plate":                int(737),
	"pale_oak_pressure_plate":                int(738),
	"mangrove_pressure_plate":                int(739),
	"bamboo_pressure_plate":                  int(740),
	"crimson_pressure_plate":                 int(741),
	"warped_pressure_plate":                  int(742),
	"iron_door":                              int(743),
	"oak_door":                               int(744),
	"spruce_door":                            int(745),
	"birch_door":                             int(746),
	"jungle_door":                            int(747),
	"acacia_door":                            int(748),
	"cherry_door":                            int(749),
	"dark_oak_door":                          int(750),
	"pale_oak_door":                          int(751),
	"mangrove_door":                          int(752),
	"bamboo_door":                            int(753),
	"crimson_door":                           int(754),
	"warped_door":                            int(755),
	"copper_door":                            int(756),
	"exposed_copper_door":                    int(757),
	"weathered_copper_door":                  int(758),
	"oxidized_copper_door":                   int(759),
	"waxed_copper_door":                      int(760),
	"waxed_exposed_copper_door":              int(761),
	"waxed_weathered_copper_door":            int(762),
	"waxed_oxidized_copper_door":             int(763),
	"iron_trapdoor":                          int(764),
	"oak_trapdoor":                           int(765),
	"spruce_trapdoor":                        int(766),
	"birch_trapdoor":                         int(767),
	"jungle_trapdoor":                        int(768),
	"acacia_trapdoor":                        int(769),
	"cherry_trapdoor":                        int(770),
	"dark_oak_trapdoor":                      int(771),
	"pale_oak_trapdoor":                      int(772),
	"mangrove_trapdoor":                      int(773),
	"bamboo_trapdoor":                        int(774),
	"crimson_trapdoor":                       int(775),
	"warped_trapdoor":                        int(776),
	"copper_trapdoor":                        int(777),
	"exposed_copper_trapdoor":                int(778),
	"weathered_copper_trapdoor":              int(779),
	"oxidized_copper_trapdoor":               int(780),
	"waxed_copper_trapdoor":                  int(781),
	"waxed_exposed_copper_trapdoor":          int(782),
	"waxed_weathered_copper_trapdoor":        int(783),
	"waxed_oxidized_copper_trapdoor":         int(784),
	"oak_fence_gate":                         int(785),
	"spruce_fence_gate":                      int(786),
	"birch_fence_gate":                       int(787),
	"jungle_fence_gate":                      int(788),
	"acacia_fence_gate":                      int(789),
	"cherry_fence_gate":                      int(790),
	"dark_oak_fence_gate":                    int(791),
	"pale_oak_fence_gate":                    int(792),
	"mangrove_fence_gate":                    int(793),
	"bamboo_fence_gate":                      int(794),
	"crimson_fence_gate":                     int(795),
	"warped_fence_gate":                      int(796),
	"powered_rail":                           int(797),
	"detector_rail":                          int(798),
	"rail":                                   int(799),
	"activator_rail":                         int(800),
	"saddle":                                 int(801),
	"white_harness":                          int(802),
	"orange_harness":                         int(803),
	"magenta_harness":                        int(804),
	"light_blue_harness":                     int(805),
	"yellow_harness":                         int(806),
	"lime_harness":                           int(807),
	"pink_harness":                           int(808),
	"gray_harness":                           int(809),
	"light_gray_harness":                     int(810),
	"cyan_harness":                           int(811),
	"purple_harness":                         int(812),
	"blue_harness":                           int(813),
	"brown_harness":                          int(814),
	"green_harness":                          int(815),
	"red_harness":                            int(816),
	"black_harness":                          int(817),
	"minecart":                               int(818),
	"chest_minecart":                         int(819),
	"furnace_minecart":                       int(820),
	"tnt_minecart":                           int(821),
	"hopper_minecart":                        int(822),
	"carrot_on_a_stick":                      int(823),
	"warped_fungus_on_a_stick":               int(824),
	"phantom_membrane":                       int(825),
	"elytra":                                 int(826),
	"oak_boat":                               int(827),
	"oak_chest_boat":                         int(828),
	"spruce_boat":                            int(829),
	"spruce_chest_boat":                      int(830),
	"birch_boat":                             int(831),
	"birch_chest_boat":                       int(832),
	"jungle_boat":                            int(833),
	"jungle_chest_boat":                      int(834),
	"acacia_boat":                            int(835),
	"acacia_chest_boat":                      int(836),
	"cherry_boat":                            int(837),
	"cherry_chest_boat":                      int(838),
	"dark_oak_boat":                          int(839),
	"dark_oak_chest_boat":                    int(840),
	"pale_oak_boat":                          int(841),
	"pale_oak_chest_boat":                    int(842),
	"mangrove_boat":                          int(843),
	"mangrove_chest_boat":                    int(844),
	"bamboo_raft":                            int(845),
	"bamboo_chest_raft":                      int(846),
	"structure_block":                        int(847),
	"jigsaw":                                 int(848),
	"test_block":                             int(849),
	"test_instance_block":                    int(850),
	"turtle_helmet":                          int(851),
	"turtle_scute":                           int(852),
	"armadillo_scute":                        int(853),
	"wolf_armor":                             int(854),
	"flint_and_steel":                        int(855),
	"bowl":                                   int(856),
	"apple":                                  int(857),
	"bow":                                    int(858),
	"arrow":                                  int(859),
	"coal":                                   int(860),
	"charcoal":                               int(861),
	"diamond":                                int(862),
	"emerald":                                int(863),
	"lapis_lazuli":                           int(864),
	"quartz":                                 int(865),
	"amethyst_shard":                         int(866),
	"raw_iron":                               int(867),
	"iron_ingot":                             int(868),
	"raw_copper":                             int(869),
	"copper_ingot":                           int(870),
	"raw_gold":                               int(871),
	"gold_ingot":                             int(872),
	"netherite_ingot":                        int(873),
	"netherite_scrap":                        int(874),
	"wooden_sword":                           int(875),
	"wooden_shovel":                          int(876),
	"wooden_pickaxe":                         int(877),
	"wooden_axe":                             int(878),
	"wooden_hoe":                             int(879),
	"stone_sword":                            int(880),
	"stone_shovel":                           int(881),
	"stone_pickaxe":                          int(882),
	"stone_axe":                              int(883),
	"stone_hoe":                              int(884),
	"golden_sword":                           int(885),
	"golden_shovel":                          int(886),
	"golden_pickaxe":                         int(887),
	"golden_axe":                             int(888),
	"golden_hoe":                             int(889),
	"iron_sword":                             int(890),
	"iron_shovel":                            int(891),
	"iron_pickaxe":                           int(892),
	"iron_axe":                               int(893),
	"iron_hoe":                               int(894),
	"diamond_sword":                          int(895),
	"diamond_shovel":                         int(896),
	"diamond_pickaxe":                        int(897),
	"diamond_axe":                            int(898),
	"diamond_hoe":                            int(899),
	"netherite_sword":                        int(900),
	"netherite_shovel":                       int(901),
	"netherite_pickaxe":                      int(902),
	"netherite_axe":                          int(903),
	"netherite_hoe":                          int(904),
	"stick":                                  int(905),
	"mushroom_stew":                          int(906),
	"string":                                 int(907),
	"feather":                                int(908),
	"gunpowder":                              int(909),
	"wheat_seeds":                            int(910),
	"wheat":                                  int(911),
	"bread":                                  int(912),
	"leather_helmet":                         int(913),
	"leather_chestplate":                     int(914),
	"leather_leggings":                       int(915),
	"leather_boots":                          int(916),
	"chainmail_helmet":                       int(917),
	"chainmail_chestplate":                   int(918),
	"chainmail_leggings":                     int(919),
	"chainmail_boots":                        int(920),
	"iron_helmet":                            int(921),
	"iron_chestplate":                        int(922),
	"iron_leggings":                          int(923),
	"iron_boots":                             int(924),
	"diamond_helmet":                         int(925),
	"diamond_chestplate":                     int(926),
	"diamond_leggings":                       int(927),
	"diamond_boots":                          int(928),
	"golden_helmet":                          int(929),
	"golden_chestplate":                      int(930),
	"golden_leggings":                        int(931),
	"golden_boots":                           int(932),
	"netherite_helmet":                       int(933),
	"netherite_chestplate":                   int(934),
	"netherite_leggings":                     int(935),
	"netherite_boots":                        int(936),
	"flint":                                  int(937),
	"porkchop":                               int(938),
	"cooked_porkchop":                        int(939),
	"painting":                               int(940),
	"golden_apple":                           int(941),
	"enchanted_golden_apple":                 int(942),
	"oak_sign":                               int(943),
	"spruce_sign":                            int(944),
	"birch_sign":                             int(945),
	"jungle_sign":                            int(946),
	"acacia_sign":                            int(947),
	"cherry_sign":                            int(948),
	"dark_oak_sign":                          int(949),
	"pale_oak_sign":                          int(950),
	"mangrove_sign":                          int(951),
	"bamboo_sign":                            int(952),
	"crimson_sign":                           int(953),
	"warped_sign":                            int(954),
	"oak_hanging_sign":                       int(955),
	"spruce_hanging_sign":                    int(956),
	"birch_hanging_sign":                     int(957),
	"jungle_hanging_sign":                    int(958),
	"acacia_hanging_sign":                    int(959),
	"cherry_hanging_sign":                    int(960),
	"dark_oak_hanging_sign":                  int(961),
	"pale_oak_hanging_sign":                  int(962),
	"mangrove_hanging_sign":                  int(963),
	"bamboo_hanging_sign":                    int(964),
	"crimson_hanging_sign":                   int(965),
	"warped_hanging_sign":                    int(966),
	"bucket":                                 int(967),
	"water_bucket":                           int(968),
	"lava_bucket":                            int(969),
	"powder_snow_bucket":                     int(970),
	"snowball":                               int(971),
	"leather":                                int(972),
	"milk_bucket":                            int(973),
	"pufferfish_bucket":                      int(974),
	"salmon_bucket":                          int(975),
	"cod_bucket":                             int(976),
	"tropical_fish_bucket":                   int(977),
	"axolotl_bucket":                         int(978),
	"tadpole_bucket":                         int(979),
	"brick":                                  int(980),
	"clay_ball":                              int(981),
	"dried_kelp_block":                       int(982),
	"paper":                                  int(983),
	"book":                                   int(984),
	"slime_ball":                             int(985),
	"egg":                                    int(986),
	"blue_egg":                               int(987),
	"brown_egg":                              int(988),
	"compass":                                int(989),
	"recovery_compass":                       int(990),
	"bundle":                                 int(991),
	"white_bundle":                           int(992),
	"orange_bundle":                          int(993),
	"magenta_bundle":                         int(994),
	"light_blue_bundle":                      int(995),
	"yellow_bundle":                          int(996),
	"lime_bundle":                            int(997),
	"pink_bundle":                            int(998),
	"gray_bundle":                            int(999),
	"light_gray_bundle":                      int(1000),
	"cyan_bundle":                            int(1001),
	"purple_bundle":                          int(1002),
	"blue_bundle":                            int(1003),
	"brown_bundle":                           int(1004),
	"green_bundle":                           int(1005),
	"red_bundle":                             int(1006),
	"black_bundle":                           int(1007),
	"fishing_rod":                            int(1008),
	"clock":                                  int(1009),
	"spyglass":                               int(1010),
	"glowstone_dust":                         int(1011),
	"cod":                                    int(1012),
	"salmon":                                 int(1013),
	"tropical_fish":                          int(1014),
	"pufferfish":                             int(1015),
	"cooked_cod":                             int(1016),
	"cooked_salmon":                          int(1017),
	"ink_sac":                                int(1018),
	"glow_ink_sac":                           int(1019),
	"cocoa_beans":                            int(1020),
	"white_dye":                              int(1021),
	"orange_dye":                             int(1022),
	"magenta_dye":                            int(1023),
	"light_blue_dye":                         int(1024),
	"yellow_dye":                             int(1025),
	"lime_dye":                               int(1026),
	"pink_dye":                               int(1027),
	"gray_dye":                               int(1028),
	"light_gray_dye":                         int(1029),
	"cyan_dye":                               int(1030),
	"purple_dye":                             int(1031),
	"blue_dye":                               int(1032),
	"brown_dye":                              int(1033),
	"green_dye":                              int(1034),
	"red_dye":                                int(1035),
	"black_dye":                              int(1036),
	"bone_meal":                              int(1037),
	"bone":                                   int(1038),
	"sugar":                                  int(1039),
	"cake":                                   int(1040),
	"white_bed":                              int(1041),
	"orange_bed":                             int(1042),
	"magenta_bed":                            int(1043),
	"light_blue_bed":                         int(1044),
	"yellow_bed":                             int(1045),
	"lime_bed":                               int(1046),
	"pink_bed":                               int(1047),
	"gray_bed":                               int(1048),
	"light_gray_bed":                         int(1049),
	"cyan_bed":                               int(1050),
	"purple_bed":                             int(1051),
	"blue_bed":                               int(1052),
	"brown_bed":                              int(1053),
	"green_bed":                              int(1054),
	"red_bed":                                int(1055),
	"black_bed":                              int(1056),
	"cookie":                                 int(1057),
	"crafter":                                int(1058),
	"filled_map":                             int(1059),
	"shears":                                 int(1060),
	"melon_slice":                            int(1061),
	"dried_kelp":                             int(1062),
	"pumpkin_seeds":                          int(1063),
	"melon_seeds":                            int(1064),
	"beef":                                   int(1065),
	"cooked_beef":                            int(1066),
	"chicken":                                int(1067),
	"cooked_chicken":                         int(1068),
	"rotten_flesh":                           int(1069),
	"ender_pearl":                            int(1070),
	"blaze_rod":                              int(1071),
	"ghast_tear":                             int(1072),
	"gold_nugget":                            int(1073),
	"nether_wart":                            int(1074),
	"glass_bottle":                           int(1075),
	"potion":                                 int(1076),
	"spider_eye":                             int(1077),
	"fermented_spider_eye":                   int(1078),
	"blaze_powder":                           int(1079),
	"magma_cream":                            int(1080),
	"brewing_stand":                          int(1081),
	"cauldron":                               int(1082),
	"ender_eye":                              int(1083),
	"glistering_melon_slice":                 int(1084),
	"armadillo_spawn_egg":                    int(1085),
	"allay_spawn_egg":                        int(1086),
	"axolotl_spawn_egg":                      int(1087),
	"bat_spawn_egg":                          int(1088),
	"bee_spawn_egg":                          int(1089),
	"blaze_spawn_egg":                        int(1090),
	"bogged_spawn_egg":                       int(1091),
	"breeze_spawn_egg":                       int(1092),
	"cat_spawn_egg":                          int(1093),
	"camel_spawn_egg":                        int(1094),
	"cave_spider_spawn_egg":                  int(1095),
	"chicken_spawn_egg":                      int(1096),
	"cod_spawn_egg":                          int(1097),
	"cow_spawn_egg":                          int(1098),
	"creeper_spawn_egg":                      int(1099),
	"dolphin_spawn_egg":                      int(1100),
	"donkey_spawn_egg":                       int(1101),
	"drowned_spawn_egg":                      int(1102),
	"elder_guardian_spawn_egg":               int(1103),
	"ender_dragon_spawn_egg":                 int(1104),
	"enderman_spawn_egg":                     int(1105),
	"endermite_spawn_egg":                    int(1106),
	"evoker_spawn_egg":                       int(1107),
	"fox_spawn_egg":                          int(1108),
	"frog_spawn_egg":                         int(1109),
	"ghast_spawn_egg":                        int(1110),
	"happy_ghast_spawn_egg":                  int(1111),
	"glow_squid_spawn_egg":                   int(1112),
	"goat_spawn_egg":                         int(1113),
	"guardian_spawn_egg":                     int(1114),
	"hoglin_spawn_egg":                       int(1115),
	"horse_spawn_egg":                        int(1116),
	"husk_spawn_egg":                         int(1117),
	"iron_golem_spawn_egg":                   int(1118),
	"llama_spawn_egg":                        int(1119),
	"magma_cube_spawn_egg":                   int(1120),
	"mooshroom_spawn_egg":                    int(1121),
	"mule_spawn_egg":                         int(1122),
	"ocelot_spawn_egg":                       int(1123),
	"panda_spawn_egg":                        int(1124),
	"parrot_spawn_egg":                       int(1125),
	"phantom_spawn_egg":                      int(1126),
	"pig_spawn_egg":                          int(1127),
	"piglin_spawn_egg":                       int(1128),
	"piglin_brute_spawn_egg":                 int(1129),
	"pillager_spawn_egg":                     int(1130),
	"polar_bear_spawn_egg":                   int(1131),
	"pufferfish_spawn_egg":                   int(1132),
	"rabbit_spawn_egg":                       int(1133),
	"ravager_spawn_egg":                      int(1134),
	"salmon_spawn_egg":                       int(1135),
	"sheep_spawn_egg":                        int(1136),
	"shulker_spawn_egg":                      int(1137),
	"silverfish_spawn_egg":                   int(1138),
	"skeleton_spawn_egg":                     int(1139),
	"skeleton_horse_spawn_egg":               int(1140),
	"slime_spawn_egg":                        int(1141),
	"sniffer_spawn_egg":                      int(1142),
	"snow_golem_spawn_egg":                   int(1143),
	"spider_spawn_egg":                       int(1144),
	"squid_spawn_egg":                        int(1145),
	"stray_spawn_egg":                        int(1146),
	"strider_spawn_egg":                      int(1147),
	"tadpole_spawn_egg":                      int(1148),
	"trader_llama_spawn_egg":                 int(1149),
	"tropical_fish_spawn_egg":                int(1150),
	"turtle_spawn_egg":                       int(1151),
	"vex_spawn_egg":                          int(1152),
	"villager_spawn_egg":                     int(1153),
	"vindicator_spawn_egg":                   int(1154),
	"wandering_trader_spawn_egg":             int(1155),
	"warden_spawn_egg":                       int(1156),
	"witch_spawn_egg":                        int(1157),
	"wither_spawn_egg":                       int(1158),
	"wither_skeleton_spawn_egg":              int(1159),
	"wolf_spawn_egg":                         int(1160),
	"zoglin_spawn_egg":                       int(1161),
	"creaking_spawn_egg":                     int(1162),
	"zombie_spawn_egg":                       int(1163),
	"zombie_horse_spawn_egg":                 int(1164),
	"zombie_villager_spawn_egg":              int(1165),
	"zombified_piglin_spawn_egg":             int(1166),
	"experience_bottle":                      int(1167),
	"fire_charge":                            int(1168),
	"wind_charge":                            int(1169),
	"writable_book":                          int(1170),
	"written_book":                           int(1171),
	"breeze_rod":                             int(1172),
	"mace":                                   int(1173),
	"item_frame":                             int(1174),
	"glow_item_frame":                        int(1175),
	"flower_pot":                             int(1176),
	"carrot":                                 int(1177),
	"potato":                                 int(1178),
	"baked_potato":                           int(1179),
	"poisonous_potato":                       int(1180),
	"map":                                    int(1181),
	"golden_carrot":                          int(1182),
	"skeleton_skull":                         int(1183),
	"wither_skeleton_skull":                  int(1184),
	"player_head":                            int(1185),
	"zombie_head":                            int(1186),
	"creeper_head":                           int(1187),
	"dragon_head":                            int(1188),
	"piglin_head":                            int(1189),
	"nether_star":                            int(1190),
	"pumpkin_pie":                            int(1191),
	"firework_rocket":                        int(1192),
	"firework_star":                          int(1193),
	"enchanted_book":                         int(1194),
	"nether_brick":                           int(1195),
	"resin_brick":                            int(1196),
	"prismarine_shard":                       int(1197),
	"prismarine_crystals":                    int(1198),
	"rabbit":                                 int(1199),
	"cooked_rabbit":                          int(1200),
	"rabbit_stew":                            int(1201),
	"rabbit_foot":                            int(1202),
	"rabbit_hide":                            int(1203),
	"armor_stand":                            int(1204),
	"iron_horse_armor":                       int(1205),
	"golden_horse_armor":                     int(1206),
	"diamond_horse_armor":                    int(1207),
	"leather_horse_armor":                    int(1208),
	"lead":                                   int(1209),
	"name_tag":                               int(1210),
	"command_block_minecart":                 int(1211),
	"mutton":                                 int(1212),
	"cooked_mutton":                          int(1213),
	"white_banner":                           int(1214),
	"orange_banner":                          int(1215),
	"magenta_banner":                         int(1216),
	"light_blue_banner":                      int(1217),
	"yellow_banner":                          int(1218),
	"lime_banner":                            int(1219),
	"pink_banner":                            int(1220),
	"gray_banner":                            int(1221),
	"light_gray_banner":                      int(1222),
	"cyan_banner":                            int(1223),
	"purple_banner":                          int(1224),
	"blue_banner":                            int(1225),
	"brown_banner":                           int(1226),
	"green_banner":                           int(1227),
	"red_banner":                             int(1228),
	"black_banner":                           int(1229),
	"end_crystal":                            int(1230),
	"chorus_fruit":                           int(1231),
	"popped_chorus_fruit":                    int(1232),
	"torchflower_seeds":                      int(1233),
	"pitcher_pod":                            int(1234),
	"beetroot":                               int(1235),
	"beetroot_seeds":                         int(1236),
	"beetroot_soup":                          int(1237),
	"dragon_breath":                          int(1238),
	"splash_potion":                          int(1239),
	"spectral_arrow":                         int(1240),
	"tipped_arrow":                           int(1241),
	"lingering_potion":                       int(1242),
	"shield":                                 int(1243),
	"totem_of_undying":                       int(1244),
	"shulker_shell":                          int(1245),
	"iron_nugget":                            int(1246),
	"knowledge_book":                         int(1247),
	"debug_stick":                            int(1248),
	"music_disc_13":                          int(1249),
	"music_disc_cat":                         int(1250),
	"music_disc_blocks":                      int(1251),
	"music_disc_chirp":                       int(1252),
	"music_disc_creator":                     int(1253),
	"music_disc_creator_music_box":           int(1254),
	"music_disc_far":                         int(1255),
	"music_disc_lava_chicken":                int(1256),
	"music_disc_mall":                        int(1257),
	"music_disc_mellohi":                     int(1258),
	"music_disc_stal":                        int(1259),
	"music_disc_strad":                       int(1260),
	"music_disc_ward":                        int(1261),
	"music_disc_11":                          int(1262),
	"music_disc_wait":                        int(1263),
	"music_disc_otherside":                   int(1264),
	"music_disc_relic":                       int(1265),
	"music_disc_5":                           int(1266),
	"music_disc_pigstep":                     int(1267),
	"music_disc_precipice":                   int(1268),
	"music_disc_tears":                       int(1269),
	"disc_fragment_5":                        int(1270),
	"trident":                                int(1271),
	"nautilus_shell":                         int(1272),
	"heart_of_the_sea":                       int(1273),
	"crossbow":                               int(1274),
	"suspicious_stew":                        int(1275),
	"loom":                                   int(1276),
	"flower_banner_pattern":                  int(1277),
	"creeper_banner_pattern":                 int(1278),
	"skull_banner_pattern":                   int(1279),
	"mojang_banner_pattern":                  int(1280),
	"globe_banner_pattern":                   int(1281),
	"piglin_banner_pattern":                  int(1282),
	"flow_banner_pattern":                    int(1283),
	"guster_banner_pattern":                  int(1284),
	"field_masoned_banner_pattern":           int(1285),
	"bordure_indented_banner_pattern":        int(1286),
	"goat_horn":                              int(1287),
	"composter":                              int(1288),
	"barrel":                                 int(1289),
	"smoker":                                 int(1290),
	"blast_furnace":                          int(1291),
	"cartography_table":                      int(1292),
	"fletching_table":                        int(1293),
	"grindstone":                             int(1294),
	"smithing_table":                         int(1295),
	"stonecutter":                            int(1296),
	"bell":                                   int(1297),
	"lantern":                                int(1298),
	"soul_lantern":                           int(1299),
	"sweet_berries":                          int(1300),
	"glow_berries":                           int(1301),
	"campfire":                               int(1302),
	"soul_campfire":                          int(1303),
	"shroomlight":                            int(1304),
	"honeycomb":                              int(1305),
	"bee_nest":                               int(1306),
	"beehive":                                int(1307),
	"honey_bottle":                           int(1308),
	"honeycomb_block":                        int(1309),
	"lodestone":                              int(1310),
	"crying_obsidian":                        int(1311),
	"blackstone":                             int(1312),
	"blackstone_slab":                        int(1313),
	"blackstone_stairs":                      int(1314),
	"gilded_blackstone":                      int(1315),
	"polished_blackstone":                    int(1316),
	"polished_blackstone_slab":               int(1317),
	"polished_blackstone_stairs":             int(1318),
	"chiseled_polished_blackstone":           int(1319),
	"polished_blackstone_bricks":             int(1320),
	"polished_blackstone_brick_slab":         int(1321),
	"polished_blackstone_brick_stairs":       int(1322),
	"cracked_polished_blackstone_bricks":     int(1323),
	"respawn_anchor":                         int(1324),
	"candle":                                 int(1325),
	"white_candle":                           int(1326),
	"orange_candle":                          int(1327),
	"magenta_candle":                         int(1328),
	"light_blue_candle":                      int(1329),
	"yellow_candle":                          int(1330),
	"lime_candle":                            int(1331),
	"pink_candle":                            int(1332),
	"gray_candle":                            int(1333),
	"light_gray_candle":                      int(1334),
	"cyan_candle":                            int(1335),
	"purple_candle":                          int(1336),
	"blue_candle":                            int(1337),
	"brown_candle":                           int(1338),
	"green_candle":                           int(1339),
	"red_candle":                             int(1340),
	"black_candle":                           int(1341),
	"small_amethyst_bud":                     int(1342),
	"medium_amethyst_bud":                    int(1343),
	"large_amethyst_bud":                     int(1344),
	"amethyst_cluster":                       int(1345),
	"pointed_dripstone":                      int(1346),
	"ochre_froglight":                        int(1347),
	"verdant_froglight":                      int(1348),
	"pearlescent_froglight":                  int(1349),
	"frogspawn":                              int(1350),
	"echo_shard":                             int(1351),
	"brush":                                  int(1352),
	"netherite_upgrade_smithing_template":    int(1353),
	"sentry_armor_trim_smithing_template":    int(1354),
	"dune_armor_trim_smithing_template":      int(1355),
	"coast_armor_trim_smithing_template":     int(1356),
	"wild_armor_trim_smithing_template":      int(1357),
	"ward_armor_trim_smithing_template":      int(1358),
	"eye_armor_trim_smithing_template":       int(1359),
	"vex_armor_trim_smithing_template":       int(1360),
	"tide_armor_trim_smithing_template":      int(1361),
	"snout_armor_trim_smithing_template":     int(1362),
	"rib_armor_trim_smithing_template":       int(1363),
	"spire_armor_trim_smithing_template":     int(1364),
	"wayfinder_armor_trim_smithing_template": int(1365),
	"shaper_armor_trim_smithing_template":    int(1366),
	"silence_armor_trim_smithing_template":   int(1367),
	"raiser_armor_trim_smithing_template":    int(1368),
	"host_armor_trim_smithing_template":      int(1369),
	"flow_armor_trim_smithing_template":      int(1370),
	"bolt_armor_trim_smithing_template":      int(1371),
	"angler_pottery_sherd":                   int(1372),
	"archer_pottery_sherd":                   int(1373),
	"arms_up_pottery_sherd":                  int(1374),
	"blade_pottery_sherd":                    int(1375),
	"brewer_pottery_sherd":                   int(1376),
	"burn_pottery_sherd":                     int(1377),
	"danger_pottery_sherd":                   int(1378),
	"explorer_pottery_sherd":                 int(1379),
	"flow_pottery_sherd":                     int(1380),
	"friend_pottery_sherd":                   int(1381),
	"guster_pottery_sherd":                   int(1382),
	"heart_pottery_sherd":                    int(1383),
	"heartbreak_pottery_sherd":               int(1384),
	"howl_pottery_sherd":                     int(1385),
	"miner_pottery_sherd":                    int(1386),
	"mourner_pottery_sherd":                  int(1387),
	"plenty_pottery_sherd":                   int(1388),
	"prize_pottery_sherd":                    int(1389),
	"scrape_pottery_sherd":                   int(1390),
	"sheaf_pottery_sherd":                    int(1391),
	"shelter_pottery_sherd":                  int(1392),
	"skull_pottery_sherd":                    int(1393),
	"snort_pottery_sherd":                    int(1394),
	"copper_grate":                           int(1395),
	"exposed_copper_grate":                   int(1396),
	"weathered_copper_grate":                 int(1397),
	"oxidized_copper_grate":                  int(1398),
	"waxed_copper_grate":                     int(1399),
	"waxed_exposed_copper_grate":             int(1400),
	"waxed_weathered_copper_grate":           int(1401),
	"waxed_oxidized_copper_grate":            int(1402),
	"copper_bulb":                            int(1403),
	"exposed_copper_bulb":                    int(1404),
	"weathered_copper_bulb":                  int(1405),
	"oxidized_copper_bulb":                   int(1406),
	"waxed_copper_bulb":                      int(1407),
	"waxed_exposed_copper_bulb":              int(1408),
	"waxed_weathered_copper_bulb":            int(1409),
	"waxed_oxidized_copper_bulb":             int(1410),
	"trial_spawner":                          int(1411),
	"trial_key":                              int(1412),
	"ominous_trial_key":                      int(1413),
	"vault":                                  int(1414),
	"ominous_bottle":                         int(1415),
}

// GetItemID returns the ID for an item name.
func GetItemID(name string) (int, bool) {
	id, ok := ItemNameToID[name]
	return id, ok
}
